# Generated by Django 5.2.5 on 2025-08-10 14:47

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('cdn_path', models.CharField(help_text='Path on CDN or signed URL template', max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('max_simultaneous_streams', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'mobile'), ('tablet', 'tablet'), ('tv', 'tv'), ('browser', 'browser'), ('other', 'other')], default='other', max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(default=datetime.datetime(2025, 8, 10, 14, 47, 28, 306021, tzinfo=datetime.timezone.utc))),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playback.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=datetime.datetime(2025, 8, 10, 14, 47, 28, 306429, tzinfo=datetime.timezone.utc))),
                ('last_heartbeat', models.DateTimeField(default=datetime.datetime(2025, 8, 10, 14, 47, 28, 306433, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('active', 'active'), ('ended', 'ended'), ('expired', 'expired')], default='active', max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='playback.device')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='playback.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='playback_wa_user_id_24979e_idx'), models.Index(fields=['last_heartbeat'], name='playback_wa_last_he_918b2a_idx')],
            },
        ),
    ]
