# Generated by Django 5.2.5 on 2025-08-11 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchsession',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 17, 10, 26, 116870, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='watchsession',
            name='last_heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 17, 10, 26, 117397, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='watchsession',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 17, 10, 26, 117393, tzinfo=datetime.timezone.utc)),
        ),
    ]
