# Generated by Django 5.2.5 on 2025-08-12 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0002_watchsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='watchsession',
            name='last_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='watchsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
